---
benchmark_config:
  generic:
    benchmark: faux
    cpus: 0
    transparent_hugepages: madvise
collector_config:
  generic:
    poll_rate: 0.1
    output_dir: data
    output_graphs: true
    hooks:
      - page_fault
      - process_trace
      - memory_usage
      - mm_rss_stat
